### ISSUE TITLE
Contribution: headers not correctly linked

### ISSUE THREAD

**Issue by RudraNilBasu** [BytesClub/BytesClub.github.io#5]
The "tips for contributing" link in contribution>For Beginners>Solving an issue> 2nd point is not correctly assigned, as a result, the link is not working correctly.

**Comment by devutsav** [comment]
@RudraNilBasu Where to link?

**Comment by RudraNilBasu** [comment]
@devutsav this link: https://bytesclub.github.io/contributing/

Under the sub-heading "Solving an issue", last bullet point. There is a link that says "tips for contributing" and it links to #tips-for-contributing but that header does not exist. It should be #tips-for-contribution
